### ISSUE TITLE
Autocomplete feature request

### ISSUE THREAD

**Issue by nigeltiany** [cheonhyangzhang/paper-tags-input#20]
Thank you for the good work. 

A suggestion feature would be so great. 

```
<paper-tag-input
    tag-suggestions="idOfIronAjaxElemThatKnowsWhereToLook"
    >
</paper-tags-input>
```

**Comment by cheonhyangzhang** [comment]
Hi @nigeltiany 
Thanks for the suggestions.

Do so what will this iron ajax element return? 
I believe that this iron ajax will have a url that will return some data, right? 
What kind of data it's returning?

**Comment by nigeltiany** [comment]
Hello @cheonhyangzhang 

It would return an array.

Here is the flow i have in mind.

The paper-tags-input element could have another property that helps the traverse the array for required visual output. What i mean for example...

A server api endpoint somewhere could have the following data

``` JSON
[
  {
     "firstname" : "James",
     "lastname" : "Bond",
     "images" : {
          "square" : "http://urltosomeimage.com/250/250"
       }
  },
  {
     "firstname" : "Indiana",
     "lastname" : "Jones",
     "images" : {
          "square" : null,
          "rectangle" : "http://urltosomeimage.com/650/250"
     }
  }
]
```

An iron ajax element could then be setup to get the above data

``` html
<iron-ajax
    id="getFamousActors"
    url="https://api.people.com/famousActors"
    handle-as="json"
    last-response="{{jsonData}}">
</iron-ajax>
```

Paper-tags-input can look like

``` html
<paper-tag-input
    tag-suggestions-ajax="getFamousActors"
    tag-suggestions="{{jsonData}}"
    suggestions-text=" 'firstname' + 'lastname' "
    suggestions-image=" 'images.square' "
    >
</paper-tags-input>
```

When paper-tags-input is on focus, it could use the id set in 'tag-suggestions-ajax' attribute to call the generateRequest method on the iron-ajax element.

If suggestions-image is null it could render the firstCharacter Defined from the attribute 'suggestions-text' to upperCase

When a user types a string it could search from the value of 'tag-suggestions' thats data binded to the response of the iron-ajax which should have sent a get request on focus.  

having a 'suggestion-text' attribute would make paper-tags-input dynamic to anykind of arrays. If a response was a string array and not an array of objects, then 'suggestions-text' need not have a value and can automatically be the string in each index of the array.

**Comment by cheonhyangzhang** [comment]
@nigeltiany 
So to sum up, I think the above comments include two features:
- having tag-suggestions-ajax and tag-suggestions property to link with iron-ajax element
  As for this feature, I thinks there is no need to have a tags-suggestions-ajax property, because by using  automatic data binding delimiters ({{ }}) [Doc](https://www.polymer-project.org/1.0/docs/devguide/data-binding#two-way-bindings), then you have an iron-ajax element with 
  `<iron-ajax
  id="getFamousActors"
  url="https://api.people.com/famousActors"
  handle-as="json"
  last-response="{{jsonData}}">
  </iron-ajax>`
  as far as tag-suggestions is using the same variable jsonData, paper-tag-input will be notified with the change of jsonData. 
- To have suggestions property to provide customizable suggestion view
  I think it would be better to provide a more flexible way so that user can insert any kind of html.
  E.g
  `<paper-tag-input
  tag-suggestions-ajax="getFamousActors"
  tag-suggestions="{{jsonData}}"
  >
  <span>{{firstname}}</span><span>{{lastname}}</span>
  <img src="{{images.square}}"></img>
  </paper-tags-input>` 

Actually, I have another polymer element [paper-typeahead-input](https://github.com/cheonhyangzhang/paper-typeahead-input), which is doing typeahead input. It has autocomplete feature. Having a customizable suggestion is also a good improve there. I used to think about a way to do it but didn't succeed at that time. 

Maybe you have some thoughts on this?
